LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libc++_realme
LOCAL_MODULE_STEM := libc++
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/system/lib64
LOCAL_SRC_FILES := libc++.so
LOCAL_MULTILIB := 64
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libc_realme
LOCAL_MODULE_STEM := libc
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/system/lib64
LOCAL_SRC_FILES := libc.so
LOCAL_MULTILIB := 64
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libm_realme
LOCAL_MODULE_STEM := libm
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/system/lib64
LOCAL_SRC_FILES := libm.so
LOCAL_MULTILIB := 64
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)
