name: Build TWRP RMX3760 Android 15

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git-core \
            repo \
            gnupg \
            flex \
            bison \
            build-essential \
            zip \
            curl \
            zlib1g-dev \
            libc6-dev-i386 \
            lib32z1-dev \
            lib32ncurses6 \
            libncurses5-dev \
            libxml2-utils \
            xsltproc \
            unzip \
            python3 \
            rsync \
            cpio \
            lz4 \
            bc

      - name: Prepare repo
        run: |
          mkdir -p ~/bin
          ln -sf /usr/bin/repo ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Init TWRP Source
        run: |
          mkdir workspace
          cd workspace

          git config --global user.name "arriRgb31"
          git config --global user.email "febyyusuf12345@gmail.com"

          repo init \
            --depth=1 \
            -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git \
            -b twrp-12.1

          repo sync \
            -c \
            --force-sync \
            --no-clone-bundle \
            --no-tags \
            -j$(nproc)

      - name: Checkout Device Tree
        uses: actions/checkout@v4
        with:
          path: workspace/device/realme/RMX3760

      - name: Python
        run: |
          sudo ln -sf /usr/bin/python3 /usr/bin/python

      - name: Build
        run: |
          cd workspace

          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C

          source build/envsetup.sh

          lunch twrp_RMX3760-eng

          mka vendorbootimage -j$(nproc)

      - name: Collect
        run: |
          mkdir -p workspace/output

          cp workspace/out/target/product/RMX3760/vendor_boot.img workspace/output/ || true
          cp workspace/out/target/product/RMX3760/recovery.img workspace/output/ || true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: TWRP_RMX3760
          path: workspace/output/*
